### PR TITLE
git-stats-importer 2.0.0

### LINKED ISSUE #1: error Cannot find the remote origin url
Seems it doesn't work on my git-svn repo :disappointed: 
```
$ git-stats-importer
error Cannot find the remote origin url. Please add it.
```

### LINKED ISSUE #10: Import all my commits from all my repos
Add option to make git-stats-importer visit all the repos on my machine / working path, so I can automatically import everything.

e.g.,
`git-stats-importer --find-repos ~/projects`

### LINKED ISSUE #16: Allow this tools to be used as library
For solving #10, I'm almost sure we will need to modularize the functions from the `bin/git-stats-importer` script, and use them in the executable file as library functions.

### LINKED ISSUE #22: Async is not used

### LINKED ISSUE #24: Use parent-search
@as0n Maybe you can try to integrate [`parent-search`](https://github.com/IonicaBizau/node-parent-search) to replace [these lines](https://github.com/IonicaBizau/git-stats-importer/blob/9e047bf676410f502ebee0f278c7dd2f584fe3a2/bin/git-stats-importer#L19-L30).

### PR DESCRIPTION
**Pull request by IonicaBizau**
This is a major change in this project. The performance was improved and the functionality is compatible with `git-stats 2.0.0`.

 - Since `git-stats 2.0.0` doesn't need remote urls, a remote url in the git project is not needed anymore. Fixes #1.
 - Support for multiple emails (`git-stats-importer -e 'alice@example.com,bob@example.com`).
 - The commits history object is not modified in memory and saved only at the end. This speeds up the things *a lot*! Just think that before it was saving/reading the file every time a commit was being imported.
 - Support for recursive search for git repositories in a specified directory (`git-stats-importer --find-repos ~/my-projects`). Fixes #10.
 - This tool can now be used as library. Fixes #16.
 - :boom: `async` was not used, so I removed it. Fixes #22 
 - Use `parent-search` to search for the git repository. Fixes #24 
 - Since `git-stats 2.0.0` allows us to use custom data paths, #2 will be fixed too. :star2: 

Some other changes:

 - Relicensed under [The KINDLY License](https://github.com/IonicaBizau/kindly-license)
 - Generated documentation using Blah 2.x.x

### CODE REVIEW

**Comment by as0n** [comment]
:clap: Good job !

**Comment by IonicaBizau** [comment]
@as0n Thank you! :smile:

File: lib/index.js [hunk 1]
```diff
@@ -0,0 +1,229 @@
...
+ * @return {Stream} The stdout stream of `git log` command.
+ */
+Importer.prototype.stream = function () {
+    var args = ["log"]
+      , i = 0
+      ;
+
+    for (; i < this.emails.length; ++i) {
+        args.push("--author");
+        args.push(this.emails[i]);
```
Comment (IonicaBizau) [inline lib/index.js]: Oh, yeah––big thanks to @catcookie for [helping me to get the commits made by specific authors](http://stackoverflow.com/a/32567909/1420197). :sparkles: :cake:
